### ISSUE TITLE
Super

### ISSUE THREAD

**Issue by BogdanMakarchuk** [BoxOfDevs/BuildBattle#1]
Thank you for creating the plugin) to Quickly used.

**Comment by Ad5001** [comment]
Not finish at all !

**Comment by Ad5001** [comment]
It's not finish at all! Maybe some other devs will help me @BoxOfDevs/developers :)

**Comment by BogdanMakarchuk** [comment]
Wait for release or at least beta :)

**Comment by remotevase** [comment]
@Ad5001 sorry, I help slightly on @ImagicalGamer's buildbattle. Not much, though. Ill work on grammar in any plugins whenever ya want me to

**Comment by Ad5001** [comment]
Ok @remotevase
